from fastapi.testclient import TestClient

from main import app

client = TestClient(app)

VALID_PAYLOAD = {
    "nitrogen": 90,
    "phosphorus": 42,
    "potassium": 43,
    "temperature": 20.9,
    "humidity": 82.0,
    "ph": 6.5,
    "rainfall": 202.9,
}


def test_predict_crop_returns_503_when_model_not_trained_yet():
    response = client.post("/predict/crop", json=VALID_PAYLOAD)
    # Same convention as soil/disease: 503 if crop_recommender.joblib
    # hasn't been generated by training/train_crop_model.py yet, 200
    # once it has.
    assert response.status_code in (200, 503)
    if response.status_code == 200:
        body = response.json()
        assert "crop" in body
        assert 0.0 <= body["confidence"] <= 1.0
        assert len(body["alternatives"]) == 2


def test_predict_crop_rejects_invalid_ph():
    payload = {**VALID_PAYLOAD, "ph": 20}  # ph is capped at 14
    response = client.post("/predict/crop", json=payload)
    assert response.status_code == 422


def test_predict_crop_rejects_missing_field():
    payload = {k: v for k, v in VALID_PAYLOAD.items() if k != "rainfall"}
    response = client.post("/predict/crop", json=payload)
    assert response.status_code == 422
